#!/bin/python

__program__         = 'slDeparturesCLI'
__version__         = 'v0.1'
__author__          = 'Joakim Uddholm'
__doc__             = '''
Usage:

%s [station name or id]
'''

__API_KEY__ = 'ace842059e54f0d2f21512c4bb4465b0'

from sitecache import SiteCache


